# Generated by Django 5.1.1 on 2025-06-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_order_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_date",
            new_name="created_at",
        ),
    ]
