# Generated by Django 5.1.1 on 2025-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_user_username_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
